import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

export interface Student {
  sid: number;
  firstName: string;
  lastName: string;
  email: string;
  mailingAddress: string;
  gpa: number;
}

interface StudentRequest {
  students: Student[];
  status: string;
  message: string;
}

const Home: NextPage = () => {
  const [students, setStudents] = useState<Student[]>([]);

  const fetchStudents = async () => {
    const data = await axios.get<StudentRequest>(
      "http://localhost:3000/api/v1/get-students"
    );
    if (data.status == 200) {
      setStudents(data.data.students);
    }
  };

  useEffect(() => {
    fetchStudents();
  }, []);
  return (
    <div>
      <Head>
        <title>StudentDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <h1 className="text-center mt-5 font-bold font-sans text-3xl md:text-4xl text-gray-700">
          The StudentDB
        </h1>
      </div>

      <div className="mt-8 mx-1 sm:mx-2 md:mx-4">
        <div className="w-full overflow-x-auto pb-3 scrollbar scrollbar-thumb-gray-300 scrollbar-thin scrollbar-thumb-rounded-md lg:scrollbar-thumb-transparent lg:scrollbar-track-transparent scrollbar-track-gray-100">
          <table className="w-full table-auto border-collapse md:rounded-xl rounded-sm overflow-hidden shadow-sm">
            <thead className="text-left font-semibold text-gray-900 bg-blue-50 uppercase">
              <tr className="lg:text-lg text-sm whitespace-nowrap">
                <th className="px-3 py-2">Student ID</th>
                <th className="px-3 py-2">First Name</th>
                <th className="px-3 py-2">Last Name</th>
                <th className="px-3 py-2">Email</th>
                <th className="px-3 py-2">Mailing Address</th>
                <th className="px-3 py-2">GPA</th>
              </tr>
            </thead>
            <tbody>
              {students.length > 0
                ? students.map((student) => (
                    <tr key={student.sid + student.firstName}>
                      <td className="px-3 py-2 border">{student.sid}</td>
                      <td className="px-3 py-2 border">{student.firstName}</td>
                      <td className="px-3 py-2 border">{student.lastName}</td>
                      <td className="px-3 py-2 border">{student.email}</td>
                      <td className="px-3 py-2 border">
                        {student.mailingAddress}
                      </td>
                      <td className="px-3 py-2 border">{student.gpa}</td>
                    </tr>
                  ))
                : null}
            </tbody>
          </table>
        </div>
      </div>
      <div className="flex flex-row justify-center mt-4">
        <button
          className="flex flex-row bg-blue-500 px-4 py-3 rounded-lg items-center justify-center text-white font-semibold hover:bg-blue-600 hover:shadow-md shadow-sm"
          onClick={() => fetchStudents()}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-5 w-5 text-white mr-3"
            viewBox="0 0 20 20"
            fill="currentColor"
          >
            <path
              fillRule="evenodd"
              d="M4 2a1 1 0 011 1v2.101a7.002 7.002 0 0111.601 2.566 1 1 0 11-1.885.666A5.002 5.002 0 005.999 7H9a1 1 0 010 2H4a1 1 0 01-1-1V3a1 1 0 011-1zm.008 9.057a1 1 0 011.276.61A5.002 5.002 0 0014.001 13H11a1 1 0 110-2h5a1 1 0 011 1v5a1 1 0 11-2 0v-2.101a7.002 7.002 0 01-11.601-2.566 1 1 0 01.61-1.276z"
              clipRule="evenodd"
            />
          </svg>
          Refresh List
        </button>
      </div>
    </div>
  );
};

export default Home;
